FROM microsoft/dotnet:2.0-sdk-jessie

RUN apt-get update && apt-get install -y unzip \
	&& curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg
ENV PATH="${PATH}:/root/vsdbg/vsdbg"

COPY . /build

WORKDIR /build
RUN dotnet restore
RUN dotnet publish --configuration Debug --output /build/out

WORKDIR /build/out
ENTRYPOINT ["dotnet", "/build/out/CfMes.dll"]